myset: myset.o set.o
	gcc -Wall -ansi -pedantic -g set.o myset.o -o myset

myset.o: myset.c set.h
	gcc -c -Wall -ansi -pedantic myset.c -o myset.o

set.o: set.c set.h
	gcc -c -Wall -ansi -pedantic set.c -o set.o
